version: '3'


services:

  sleek-airflow:

    image: airflow-tp1:latest

    

    volumes:

      - ./airflow:/opt/airflow


    ports:

      - "8080:8080"


    command: airflow standalone